name: QodanaCustomImageJob
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Jetbrains Space
        uses: docker/login-action@v2
        with:
          registry: registry.jetbrains.team
          username: Irina.Khromova
          password: ${{ secrets.SPACE_PASSWORD }}
      - run: docker pull registry.jetbrains.team/p/sa/containers/qodana-cdnet:2023.3-nightly
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.1.0
        with:
          args: "--linter,registry.jetbrains.team/p/sa/containers/qodana-cdnet:2023.3-nightly"
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ runner.temp }}/qodana/results/
